In [1]:
import numpy as np
import pandas as pd
# from pandas import Series, DataFrame 
import seaborn as sns
from matplotlib import pyplot as plt

from sklearn.preprocessing import LabelEncoder, OneHotEncoder

import warnings
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, VotingClassifier
from sklearn.model_selection import cross_validate, train_test_split, GridSearchCV, cross_val_score, RandomizedSearchCV, validation_curve

# from xgboost import XGBClassifier
import lightgbm as ltb
# from catboost import CatBoostClassifier
from sklearn.linear_model import LogisticRegression
from statsmodels.stats.outliers_influence import variance_inflation_factor
from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.exceptions import ConvergenceWarning
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from xgboost import XGBRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
import joblib
from lightgbm import LGBMClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, VotingClassifier, AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier


warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter("ignore", category=ConvergenceWarning)
pd.set_option('display.width', 10000)



C:\Users\makif\anaconda3\lib\site-packages\xgboost\compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index


In [4]:
df=pd.read_csv(r"C:\Users\makif\Desktop\MAAS_HESAPLAMA\step6_encoded.csv")

In [5]:
df.head()

LEVEL  POSITION_CTO  POSITION_DATA SCIENTIST  POSITION_DATABASE ADMIN  POSITION_DEVOPS ENGINEER  POSITION_EMBEDDED SOFTWARE DEVELOPER  POSITION_FRONT-END DEVELOPER  POSITION_FULL STACK DEVELOPER  POSITION_GAME DEVELOPER  POSITION_MOBILE APPLICATION DEVELOPER  ...  COMPANY_Yazılım & Teknoloji  WORK_TYPE_Geçici Remote  WORK_TYPE_Hibrit  WORK_TYPE_Ofis  WORK_TYPE_Remote  CITY_yurt_ici  CURRENCY_GBP  CURRENCY_TRY  CURRENCY_USD  SALARY_AVG_TL
0      1             0                        0                        0                         0                                     0                             0                              0                        0                                      0  ...                            0                        0                 1               0                 0              1             0             1             0          15499
1      0             0                        0                        0                         0                                     0                             1                              0                        0                                      0  ...                            0                        0                 1               0                 0              1             0             1             0           8499
2      1             0                        0                        0                         0                                     0                             0                              0                        0                                      0  ...                            0                        0                 0               0                 1              1             0             1             0          15499
3      0             0                        0                        0                         0                                     0                             0                              1                        0                                      0  ...                            0                        0                 1               0                 0              1             0             1             0          10499
4      0             0                        0                        0                         0                                     0                             0                              0                        0                                      0  ...                            0                        0                 0               0                 0              1             0             1             0           5499

[5 rows x 33 columns]

In [8]:
def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Types #####################")
    print(dataframe.dtypes)
    print("##################### Head #####################")
    print(dataframe.head(head))
    print("##################### Tail #####################")
    print(dataframe.tail(head))
    print("##################### NA #####################")
    print(dataframe.isnull().sum())
    print("##################### Quantiles #####################")
    print(dataframe.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)

check_df(df)

##################### Shape #####################
(5026, 33)
##################### Types #####################
LEVEL                                      int64
POSITION_CTO                               int64
POSITION_DATA SCIENTIST                    int64
POSITION_DATABASE ADMIN                    int64
POSITION_DEVOPS ENGINEER                   int64
POSITION_EMBEDDED SOFTWARE DEVELOPER       int64
POSITION_FRONT-END DEVELOPER               int64
POSITION_FULL STACK DEVELOPER              int64
POSITION_GAME DEVELOPER                    int64
POSITION_MOBILE APPLICATION DEVELOPER      int64
POSITION_OTHER                             int64
POSITION_QA / TEST AUTOMATION DEVELOPER    int64
POSITION_SOFTWARE ARCHITECT                int64
POSITION_SOFTWARE DEVELOPMENT MANAGER      int64
POSITION_TEAM / TECH LEAD                  int64
GENDER_Kadın                               int64
COMPANY_Dijital / Reklam Ajansı            int64
COMPANY_E-Ticaret                          int64
COMPANY

In [70]:
#Bagımlı ve bagımsız degiskenlerimizi ayırıyoruz
X = df.drop(["SALARY_AVG_TL"], axis=1)
y = df["SALARY_AVG_TL"]

In [71]:
# Veri setini train (%80) ve test (%20) şeklinde iki parçaya ayır.
# Her çalıştırdığımızda aynı değerleri almak için random_state değerini set ettik.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)

In [72]:
# Log dönüşümünün gerçekleştirilmesi
train_df = df[df['SALARY_AVG_TL'].notnull()]
test_df = df[df['SALARY_AVG_TL'].isnull()]

In [73]:
y = np.log1p(train_df['SALARY_AVG_TL'])
X = train_df.drop("SALARY_AVG_TL", axis=1)

In [74]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)

In [75]:
lgbm = LGBMRegressor().fit(X_train, y_train)
y_pred = lgbm.predict(X_test)

y_pred

array([9.0658722 , 9.07533745, 9.05747564, ..., 9.59827306, 9.55877898,
       9.18420311])

In [76]:
# Yapılan LOG dönüşümünün tersinin (inverse'nin) alınması
new_y = np.expm1(y_pred)
new_y

array([ 8653.82455666,  8736.13359385,  8581.45808093, ...,
       14738.30570885, 14167.53560025,  9741.01354959])

In [77]:
new_y_test = np.expm1(y_test)
new_y_test

3489      5499.0
2070      7499.0
1875      5499.0
1971     15499.0
3536    204425.0
          ...   
4707      6499.0
791      25499.0
4853     11499.0
1438      6499.0
301       6499.0
Name: SALARY_AVG_TL, Length: 1006, dtype: float64

In [78]:
np.sqrt(mean_squared_error(new_y_test, new_y))

18834.10235339537

In [20]:
#LGBMRegressor Modelini Kuralım ve 
# hiperparametre optimizasyonlarını gerçekleştirelim

In [79]:
lgbm_model = LGBMRegressor(random_state=1)

In [80]:
rmse = np.mean(np.sqrt(-cross_val_score(lgbm_model, X, y, cv=5, scoring="neg_mean_squared_error")))
rmse

0.37692639905939246

In [87]:
lgbm_params = {"learning_rate": [0.01, 0.1],
               "n_estimators": [500, 700]
               #"colsample_bytree": [0.5, 0.7, 1]
             }

In [88]:
lgbm_gs_best = GridSearchCV(lgbm_model,
                            lgbm_params,
                            cv=5,
                            n_jobs=-1,
                            verbose=True).fit(X, y)

lgbm_gs_best

Fitting 5 folds for each of 4 candidates, totalling 20 fits


GridSearchCV(cv=5,
             estimator=LGBMRegressor(learning_rate=0.01, n_estimators=500,
                                     random_state=1),
             n_jobs=-1,
             param_grid={'learning_rate': [0.01, 0.1],
                         'n_estimators': [500, 700]},
             verbose=True)

In [90]:
final_model = lgbm_model.set_params(**lgbm_gs_best.best_params_).fit(X, y)

In [91]:
rmse = np.mean(np.sqrt(-cross_val_score(final_model, X, y, cv=5, scoring="neg_mean_squared_error")))
rmse

0.37583951199605103

In [93]:
model = LGBMRegressor()
model.fit(X, y)
y_pred = model.predict(df.drop("SALARY_AVG_TL", axis=1))
y_pred

array([ 9.51385819,  8.94555426,  9.56885598, ...,  9.05696517,
       10.01173597,  9.11260293])

In [94]:
y_test

3489     8.612503
2070     8.922658
1875     8.612503
1971     9.648595
3536    12.227961
          ...    
4707     8.779557
791     10.146434
4853     9.350102
1438     8.779557
301      8.779557
Name: SALARY_AVG_TL, Length: 1006, dtype: float64